### PR TITLE
Support for nested bake

### PR DESCRIPTION
**Pull request by david-zacharias**
So, this is a huge PR and with it I have modified bake at it's core, but I also wanted the ability to nest bake commands as requested in #37 and for doing so I had to change the rendering. Please take a close look and decide if you want to introduce this changes. 

**Existing tests**
The existing tests all pass. __BUT__ I made two modifications: In both files  `expected/foreach_meta.html` and `expected/render_bake.html` the new version creates on one empty line less. I have checked the processing *on paper* and would say, that these lines should not have been there (maybe this is also related to #26, but I would not vouch for it). This is why I removed them from the expected files.

After my testing I would say, the new rendering is compatible with previous one.

**New tests**
As for my other PRs I have added testing.

Okay, that's it from my side for today. What do you think?

### CODE REVIEW

**Comment by david-zacharias** [comment]
I have noticed that the new introduced `parseSignature()` fails to detect the include path when the bake statement is written in multiple lines e.g.

```HTML
<!--(bake header.tpl.html
	color="#333"
	title="Hello World!")-->
```
I have fixed. As there was no test covering multiline statements, I added one.

**Comment by MathiasPaumgarten** [comment]
Hey @david-zacharias,

wow. this is awesome. Both of your PRs look really good. I haven't had the chance too look through them in detail. But I'll be merging soon. Thanks for all that hard work.

**Comment by david-zacharias** [comment]
You are welcome! 

Also thank you: it's really great that you reply quickly. Have seen projects where this takes weeks or never happens...

When you take a closer look into the code, you may answer me one question: I have reused your regex for finding bake-tags: 

```JS
var regex = /(\n?)([ |\t]*)<!--\(\s?bake(-start|-end)?([^]*?)\)-->/;
```
I understand the expresson except this `[^]*?` or precisely the inner `[^]`. The code works and I could't come up with an working alternative... how does it do what it does? 

P.S: I just realized that this PR includes also the changes from the other PR... hope you are more git expert than I am, and you can solve this out.

**Comment by MathiasPaumgarten** [comment]
Hey, 

still have to look through it, just thought I'd get back to you real quick with two answers. 
> P.S: I just realized that this PR includes also the changes from the other PR... hope you are more git 
> expert than I am, and you can solve this out.
I am certainly no expert, but I think the reason why you have all your commits in this PR (which is totally fine btw, since I'm planning to merge all your changes) is because you wrote a set of changes, then formed a PR, and then continued to write more changes, and formed a second PR. Thus git didn't know where your chain of commits should stop. If you make a PR and then continue to commit to the same branch in your repo, it will continue pulling in the changes to the PR. 
I don't know if that answered your question or I'm just telling you things you already know. 

As for the regex: It's a doozy and I had to think about what I did there. There might be a better way, but here is the gist: 

`*?`: the `?` makes the quantifier lazy. `*` means 0 or more, as you know. `*?` means 0 or more but as little as possible with making the rest of the regex work. 

`[^]`: this is a weird one and essentially means every character. Because `[]` would be no character and the `^` negates that to the opposite, meaning every character. 

So together this thing `[^]*?` means any amount, but as little as possible, of any character so then if you add the next bit `([^]*?)\)-->` results in the meaning of: Anything until you hit the first `)-->`. 

This was my solution to allow any symbol in the the key-value pairs in the bake statement until it hits a `)-->` sequence. 

My original version allowed any character but `>`. That makes for a simple Regex but eventually was too exclusive. 

I hope that answers the question.

**Comment by david-zacharias** [comment]
Hey, thanks for the detailed information. The *weird one* was new to me. Did not know that `[]` alone works, so learned something new.

**Comment by david-zacharias** [comment]
I have tested the branch of this PR in some more projects. Thereby I found the following two bugs, which I have fixed in my latest commits:

a) Filepaths were not build correctly, when a file-include was nested inside a inline-statement. e.g.

```HTML
<!--(bake-start _if="reference.partners")-->
  <h3>Partner</h3>
  <!--(bake partner.tpl.html _foreach="partner:reference.partners")-->
<!--(bake-end)-->
```

b) Includes pathes staring with `_` where not detected by signatureRegex

```HTML
<!--(bake _my-partial.tpl.html _if="set.name)-->
```

@MathiasPaumgarten How is the review going?

**Comment by MathiasPaumgarten** [comment]
Hey @david-zacharias 

thanks for that. I wouldn't have caught that. I don't think that was covered in any test. Especially the `_` in the beginning of the file path.

Looks good to me, I will merge this now. Thanks for the patience.

**Comment by MathiasPaumgarten** [comment]
I have merged this, and bumped it to version `1.0.0` because it essentially included the refactor I've been wanting to write. 

I had a lot of not DRY code in there (in the sepeartion between inline and external bake). You cleared that all up. Thanks. This is a huge PR. 

:ship: :two_men_holding_hands:

**Comment by david-zacharias** [comment]
Thanks, I am happy to help :bowtie:

**Pull request merged**
